$commands = @(
"npx -y shadcn@latest add @forgeui/animated-otp -y",
"npx -y shadcn@latest add @forgeui/animated-tabs -y",
"npx -y shadcn@latest add @forgeui/expandable-card -y",
"npx -y shadcn@latest add @forgeui/notification-panel -y",
"npx -y shadcn@latest add @forgeui/onboard-card -y",
"npx -y shadcn@latest add @forgeui/stack-ripple -y",
"npx -y shadcn@latest add @forgeui/stats-card -y",
"npx -y shadcn@latest add @forgeui/text-reveal -y",
"npx -y shadcn@latest add @forgeui/text-shimmer -y",
"npx -y shadcn@latest add @animate-ui/components-animate-avatar-group -y",
"npx -y shadcn@latest add @animate-ui/components-animate-tabs -y",
"npx -y shadcn@latest add @animate-ui/components-radix-checkbox -y",
"npx -y shadcn@latest add @animate-ui/components-radix-alert-dialog -y",
"npx -y shadcn@latest add @animate-ui/components-radix-dialog -y",
"npx -y shadcn@latest add @animate-ui/components-radix-dropdown-menu -y",
"npx -y shadcn@latest add @animate-ui/components-radix-hover-card -y",
"npx -y shadcn@latest add @animate-ui/components-radix-progress -y",
"npx -y shadcn@latest add @animate-ui/components-radix-radio-group -y",
"npx -y shadcn@latest add @animate-ui/components-radix-sheet -y",
"npx -y shadcn@latest add @animate-ui/components-radix-sidebar -y",
"npx -y shadcn@latest add @animate-ui/components-radix-switch -y",
"npx -y shadcn@latest add @animate-ui/components-radix-toggle-group -y",
"npx -y shadcn@latest add @animate-ui/components-radix-tooltip -y",
"npx -y shadcn@latest add @animate-ui/components-buttons-copy -y",
"npx -y shadcn@latest add @animate-ui/components-buttons-icon -y",
"npx -y shadcn@latest add @animate-ui/components-buttons-ripple -y",
"npx -y shadcn@latest add @animate-ui/components-buttons-theme-toggler -y",
"npx -y shadcn@latest add @animate-ui/components-backgrounds-bubble -y",
"npx -y shadcn@latest add @animate-ui/demo-components-community-flip-card -y",
"npx -y shadcn@latest add @animate-ui/components-community-management-bar -y",
"npx -y shadcn@latest add @animate-ui/components-community-motion-carousel -y",
"npx -y shadcn@latest add @animate-ui/components-community-notification-list -y",
"npx -y shadcn@latest add @animate-ui/components-community-pin-list -y",
"npx -y shadcn@latest add @animate-ui/components-community-playful-todolist -y",
"npx -y shadcn@latest add @animate-ui/components-community-share-button -y",
"npx -y uilora@latest add 404 -y",
"npx -y uilora@latest add clay-form -y",
"npx -y uilora@latest add glass-form -y",
"npx -y uilora@latest add uilora-glass-pricing-card -y",
"npx -y uilora@latest add uilora-light-bento -y",
"npx -y uilora@latest add player-course -y",
"npx -y uilora@latest add pricing-aero -y",
"npx -y uilora@latest add timeline-glass -y",
"npx -y uilora@latest add uilora-dashboard-skeleton -y",
"npx -y uilora@latest add scroll-morph -y",
"npx -y uilora@latest add scroll-zoom -y",
"npx -y uilora@latest add classic-skeleton -y",
"npx -y uilora@latest add uilora-feed-skeleton -y",
"npx -y uilora@latest add masked-reveal -y",
"npx -y uilora@latest add type-writer -y",
"npx -y uilora@latest add flip-reveal -y",
"npx -y uilora@latest add faq-dark -y",
"npx -y uilora@latest add uilora-liquid -y",
"npx -y uilora@latest add faq-light -y",
"npx -y uilora@latest add faq-timeline -y",
"npx -y uilora@latest add striped-rows-table -y"
)

foreach ($cmd in $commands) {
    Write-Host "`n>>> Executing: $cmd"
    Invoke-Expression $cmd
}
